name: Build Ring Racers

on:
  workflow_dispatch:

jobs:
  do-everything:
    runs-on: ubuntu-latest

    env:
      VCPKG_TARGET_TRIPLET: x64-mingw-static
      CC: x86_64-w64-mingw32-gcc
      CXX: x86_64-w64-mingw32-g++
      LD: x86_64-w64-mingw32-ld

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: vcpkg
        run: |
          echo -e "\e[0Ksection_start:`date +%s`:vcpkg-root[collapsed=true]\r\e[0KSetting vcpkg cache"
          export VCPKG_DEFAULT_BINARY_CACHE="$(pwd)/build/vcpkg-binary-cache"
          mkdir -p "build/vcpkg-binary-cache"
          echo -e "\e[0Ksection_end:`date +%s`:vcpkg-root\r\e[0K"

      - name: apt_toolchain
        run: |
          echo -e "\e[0Ksection_start:`date +%s`:apt_toolchain[collapsed=true]\r\e[0KInstalling toolchain packages"
          sudo apt-get install g++-mingw-w64-x86-64-win32
          echo -e "\e[0Ksection_end:`date +%s`:apt_toolchain\r\e[0K"

      - name: apt_development
        run: |
          echo -e "\e[0Ksection_start:`date +%s`:apt_development[collapsed=true]\r\e[0KInstalling development packages"
          sudo apt-get install ninja-build
          echo -e "\e[0Ksection_end:`date +%s`:apt_development\r\e[0K"

      - name: cmake
        run: |
          sudo apt-get install nasm
          echo -e "\e[0Ksection_start:`date +%s`:cmake[collapsed=false]\r\e[0KBuilding Makefiles"
          cmake \
          --preset ninja-release \
          -B build.cmake \
          -G "Unix Makefiles" \
          -DCMAKE_COLOR_DIAGNOSTICS=OFF \
          -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/toolchains/mingw.cmake \
          -DCMAKE_TOOLCHAIN_FILE=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake \
          -DVCPKG_TARGET_TRIPLET=${VCPKG_TARGET_TRIPLET}
          echo -e "\e[0Ksection_end:`date +%s`:cmake\r\e[0K"

      - name: make
        run: |
          echo -e "\e[0Ksection_start:`date +%s`:make[collapsed=false]\r\e[0KCompiling SRB2"
          cmake --build build.cmake --parallel 1 -- --keep-going
          echo -e "\e[0Ksection_end:`date +%s`:make\r\e[0K"

      - name: zip compiled build
        run: |
          cd build.cmake/bin
          zip -r ringracers.zip .

      - name: Upload as github release
        uses: softprops/action-gh-release@v2
        with:
            tag_name: latest
            token: ${{ secrets.GITHUB_TOKEN }}
            files: build.cmake/bin/ringracers.zip